In [1]:
from utils import NerDataset

dev_dataset = NerDataset('./processed/processed_dev_bio.txt')

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.


In [3]:
len(dev_dataset.sents)

909

In [4]:
train_dataset = NerDataset('./processed/processed_training_bio.txt')
len(train_dataset)

6306

In [5]:
test_dataset[0]

('[CLS] ， 患 者 3 月 前 因 “ 直 肠 癌 ” 于 在 我 院 于 全 麻 上 行 直 肠 癌 根 治 术 （ D I X O N 术 ） ， 手 术 过 程 顺 利 ， 术 后 给 予 抗 感 染 及 营 养 支 持 治 疗 ， 患 者 恢 复 好 ， 切 口 愈 合 良 好 。 ， 术 后 病 理 示 ： 直 肠 腺 癌 （ 中 低 度 分 化 ） ， 浸 润 溃 疡 型 ， 面 积 3 . 5 * 2 C M ， 侵 达 外 膜 。 双 端 切 线 另 送 “ 近 端 ” 、 “ 远 端 ” 及 环 周 底 部 切 除 面 未 查 见 癌 。 肠 壁 一 站 （ 1 0 个 ） 、 中 间 组 （ 8 个 ） 淋 巴 结 未 查 见 癌 。 ， 免 疫 组 化 染 色 示 ： E R C C 1 弥 漫 （ + ） 、 T S 少 部 分 弱 （ + ） 、 S Y N （ - ） 、 C G A （ - ） 。 术 后 查 无 化 疗 禁 忌 后 给 予 3 周 期 化 疗 ， ， 方 案 为 ： 奥 沙 利 铂 1 5 0 M G O D 1 ， 亚 叶 酸 钙 0 . 3 G + 替 加 氟',
 [101,
  8024,
  2642,
  5442,
  124,
  3299,
  1184,
  1728,
  100,
  4684,
  5499,
  4617,
  100,
  754,
  1762,
  2769,
  7368,
  754,
  1059,
  7937,
  677,
  6121,
  4684,
  5499,
  4617,
  3418,
  3780,
  3318,
  8020,
  146,
  151,
  166,
  157,
  156,
  3318,
  8021,
  8024,
  2797,
  3318,
  6814,
  4923,
  7556,
  1164,
  8024,
  3318,
  1400,
  5314,
  750,
  2834,
  2697,
  3381,
  1350,
  5852,
  1075,
  3118,
  2898,
  3780,
  4545,
  8024,
  2642,
  5442,
  261

In [9]:
train_dataset[1]

('[CLS] ， 患 者 因 罹 患 “ 胃 癌 ” 于 2 0 1 3 - 1 0 - 2 9 在 我 院 予 行 全 麻 上 胃 癌 根 治 术 ， ， 术 中 见 ： 腹 腔 内 腹 水 ， 腹 膜 无 转 移 ， 肝 脏 未 触 及 明 显 转 移 性 灶 ， 肿 瘤 位 于 胃 体 、 胃 底 部 ， 小 弯 侧 偏 后 壁 ， 约 5 * 4 * 2 C M 大 小 ， 肿 瘤 已 侵 达 浆 膜 外 ， 第 1 、 3 组 淋 巴 结 肿 大 ， 肿 瘤 尚 能 活 动 ， 经 探 查 决 定 行 全 胃 切 除 ， 空 肠 J 字 代 胃 术 。 手 术 顺 利 ， 术 后 积 极 予 相 关 对 症 支 持 治 疗 ； ， 后 病 理 示 ： 胃 底 、 体 小 弯 侧 低 分 化 腺 癌 ， 部 分 为 印 戒 细 胞 癌 图 像 ， 蕈 伞 型 ， 面 积 5 . 2 * 3 . 5 C M ， 局 部 侵 达 粘 膜 上 层 ， 并 于 少 数 腺 管 内 查 见 癌 栓 。 双 端 切 线 及 另 送 “ 近 端 切 线 ” 未 查 见 癌 。 呈 三 组 （ 5 / 1 3 个 ） 淋 巴',
 [101,
  8024,
  2642,
  5442,
  1728,
  5395,
  2642,
  100,
  5517,
  4617,
  100,
  754,
  123,
  121,
  122,
  124,
  118,
  122,
  121,
  118,
  123,
  130,
  1762,
  2769,
  7368,
  750,
  6121,
  1059,
  7937,
  677,
  5517,
  4617,
  3418,
  3780,
  3318,
  8024,
  8024,
  3318,
  704,
  6224,
  8038,
  5592,
  5579,
  1079,
  5592,
  3717,
  8024,
  5592,
  5606,
  3187,
  6760,
  4919,
  8024,
  5498,
  5552,
  3313,
  6239,
  1350,
  3209,
  3227,
  6760,
  4919,
 

### 分段处理，使长度低于256

In [37]:
MAX_LEN = 256 - 2
sents, tags_li = [], [] # list of lists
for entry in entries:
    words = [line.split()[0] for line in entry.splitlines()]
    tags = ([line.split()[-1] for line in entry.splitlines()])
#     sents.append(["[CLS]"] + words + ["[SEP]"])  # 每个句子前后加['CLS']和['SEP']
#     tags_li.append(["<PAD>"] + tags + ["<PAD>"])
    if len(words) > MAX_LEN:
        # 先对句号分段
        word, tag = [], []
        for char, t in zip(words, tags):
            
            if char != '。':
                word.append(char)
                tag.append(t)
            else:
#                 if len(word) > MAX_LEN:
#                     word = word[:MAX_LEN]
#                     tag = tag[:MAX_LEN]
                sents.append(["[CLS]"] + word[:MAX_LEN] + ["[SEP]"])
                tags_li.append(["PAD"] + tag[:MAX_LEN] + ["PAD"])
                word, tag = [], []            
        # 最后的
        if len(word):
            sents.append(["[CLS]"] + word[:MAX_LEN] + ["[SEP]"])
            tags_li.append(["PAD"] + tag[:MAX_LEN] + ["PAD"])
            word, tag = [], []
    else:
        sents.append(["[CLS]"] + word[:MAX_LEN] + ["[SEP]"])
        tags_li.append(["PAD"] + tag[:MAX_LEN] + ["PAD"])

In [38]:
len(sents)

6306

In [39]:
len(tags_li)

6306

In [36]:
sents[0], tags_li[0]

(['，',
  '患',
  '者',
  '3',
  '月',
  '前',
  '因',
  '“',
  '直',
  '肠',
  '癌',
  '”',
  '于',
  '在',
  '我',
  '院',
  '于',
  '全',
  '麻',
  '上',
  '行',
  '直',
  '肠',
  '癌',
  '根',
  '治',
  '术',
  '（',
  'D',
  'I',
  'X',
  'O',
  'N',
  '术',
  '）',
  '，',
  '手',
  '术',
  '过',
  '程',
  '顺',
  '利',
  '，',
  '术',
  '后',
  '给',
  '予',
  '抗',
  '感',
  '染',
  '及',
  '营',
  '养',
  '支',
  '持',
  '治',
  '疗',
  '，',
  '患',
  '者',
  '恢',
  '复',
  '好',
  '，',
  '切',
  '口',
  '愈',
  '合',
  '良',
  '好',
  '。',
  '，',
  '术',
  '后',
  '病',
  '理',
  '示',
  '：',
  '直',
  '肠',
  '腺',
  '癌',
  '（',
  '中',
  '低',
  '度',
  '分',
  '化',
  '）',
  '，',
  '浸',
  '润',
  '溃',
  '疡',
  '型',
  '，',
  '面',
  '积',
  '3',
  '.',
  '5',
  '*',
  '2',
  'C',
  'M',
  '，',
  '侵',
  '达',
  '外',
  '膜',
  '。',
  '双',
  '端',
  '切',
  '线',
  '另',
  '送',
  '“',
  '近',
  '端',
  '”',
  '、',
  '“',
  '远',
  '端',
  '”',
  '及',
  '环',
  '周',
  '底',
  '部',
  '切',
  '除',
  '面',
  '未',
  '查',
  '见',
  '癌',
  '。',
  '肠',
  '壁',
  '一',
  '站',

In [2]:
from pytorch_pretrained_bert import BertModel
bert = BertModel.from_pretrained('bert-base-chinese')

In [4]:
x = dev_dataset[1]

In [9]:
import torch
encode_layers, _ = bert(torch.tensor(x[1]).unsqueeze(0))
enc = encode_layers[-1]
enc

tensor([[[-0.4081,  0.6838, -0.1342,  ..., -0.6718, -0.5864,  0.2491],
         [-0.1821,  0.4146,  0.9377,  ..., -1.1175, -0.4919,  0.0507],
         [-0.2332,  0.3116,  0.1658,  ...,  0.4438,  0.3029, -0.0686],
         ...,
         [-0.0225, -0.1823, -0.4035,  ...,  0.8034, -0.0065, -0.0556],
         [-0.5497,  0.5112,  1.1299,  ...,  0.3418, -0.0035, -0.6358],
         [-0.2669, -0.1594, -0.0355,  ...,  0.3744, -0.3602, -0.0103]]],
       grad_fn=<AddBackward0>)

In [10]:
enc.size()

torch.Size([1, 59, 768])

In [11]:
len(x[1])

59

In [14]:
enc = enc.view(len(x[1]), 1, -1)
enc.size()

torch.Size([59, 1, 768])

In [11]:
from utils import NerDataset
dev_dataset = NerDataset('./processed/processed_dev_bio.txt')

In [12]:
dev_dataset.sents[0]

['[CLS]',
 '，',
 '患',
 '者',
 '2',
 '0',
 '1',
 '1',
 '年',
 '5',
 '月',
 '1',
 '日',
 '因',
 '尿',
 '频',
 '尿',
 '急',
 '在',
 '外',
 '院',
 '检',
 '查',
 '，',
 '行',
 'B',
 '超',
 '及',
 'C',
 'T',
 '检',
 '查',
 '提',
 '示',
 '盆',
 '腔',
 '包',
 '块',
 '，',
 '建',
 '议',
 '进',
 '一',
 '步',
 '检',
 '查',
 '[SEP]']

In [13]:
dev_dataset.tags_li[0]

['<PAD>',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'B-INF',
 'I-INF',
 'O',
 'B-INF',
 'I-INF',
 'O',
 'O',
 'O',
 'O',
 'B-PAT',
 'I-PAT',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 '<PAD>']

In [14]:
for sent, tag in zip(dev_dataset.sents, dev_dataset.tags_li):
    assert len(sent) == len(tag), f"{len(sent)}, {len(tag)}"

In [7]:
from pytorch_pretrained_bert import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('/root/workspace/qa_project/chinese_L-12_H-768_A-12/')

In [8]:
VOCAB = ('<PAD>', 'O', 'B-INF', 'I-INF', 'B-PAT', 'I-PAT', 'B-OPS', 
        'I-OPS', 'B-DSE', 'I-DSE', 'B-DRG', 'I-DRG', 'B-LAB', 'I-LAB')
tag2idx = {tag: idx for idx, tag in enumerate(VOCAB)}

In [15]:
idx = 0
for words, tags in zip(dev_dataset.sents, dev_dataset.tags_li):
    x, y = [], []
    is_heads = []
    for w, t in zip(words, tags):
        tokens = tokenizer.tokenize(w) if w not in ("[CLS]", "[SEP]") else [w]
        xx = tokenizer.convert_tokens_to_ids(tokens)
        
        is_head = [1] + [0]*(len(tokens) - 1)
        t = [t] + ["<PAD>"] * (len(tokens) - 1)
        yy = [tag2idx[each] for each in t]  # (T,)

        x.extend(xx)
        is_heads.extend(is_head)
        y.extend(yy)
    assert len(x)==len(y)==len(is_heads), f"{idx}"
    idx += 1


AssertionError: 366

In [16]:
dev_dataset.sents[366]

['[CLS]',
 '术',
 '后',
 '行',
 '2',
 '周',
 '期',
 '辅',
 '助',
 '化',
 '疗',
 '，',
 '方',
 '案',
 'M',
 'F',
 'O',
 'L',
 'F',
 'O',
 'X',
 '7',
 '(',
 'O',
 'X',
 'A',
 '1',
 '0',
 '0',
 'M',
 'G',
 '/',
 'M',
 '\ue236',
 ',',
 'C',
 'F',
 '4',
 '0',
 '0',
 'M',
 'G',
 '/',
 'M',
 '\ue236',
 ',',
 '5',
 'F',
 'U',
 '2',
 '4',
 '0',
 '0',
 'M',
 'G',
 '/',
 'M',
 '\ue236',
 ')',
 '，',
 '过',
 '程',
 '顺',
 '利',
 '[SEP]']

### CRF

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
torch.manual_seed(1)

In [16]:
def argmax(vec):
    _, idx = torch.max(vec, 1)
    return idx.item()

In [17]:
def prepare_sequence(seq, to_ix):
    idxs = [to_ix[w] for w in seq]
    return torch.tensor(idxs, dtype=torch.long)

In [18]:
def log_sum_exp(vec):
    max_score = vec[0, argmax(vec)]
    max_score_broadcast = max_score.view(1, -1).expand(1, vec.size()[1])
    return max_score + \
        torch.log(torch.sum(torch.exp(vec - max_score_broadcast)))

In [19]:
START_TAG = "<START>"
STOP_TAG = "<STOP>"
EMBEDDING_DIM = 5
HIDDEN_DIM = 4

In [20]:
training_data = [(
    "the wall street journal reported today that apple corporation made money".split(),
    "B I I I O O O B I O O".split()
), (
    "georgia tech is a university in georgia".split(),
    "B I O O O O B".split()
)]
word_to_ix = {}
for sentence, tags in training_data:
    for word in sentence:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)
word_to_ix

{'the': 0,
 'wall': 1,
 'street': 2,
 'journal': 3,
 'reported': 4,
 'today': 5,
 'that': 6,
 'apple': 7,
 'corporation': 8,
 'made': 9,
 'money': 10,
 'georgia': 11,
 'tech': 12,
 'is': 13,
 'a': 14,
 'university': 15,
 'in': 16}

In [21]:
tag_to_ix = {"B": 0, "I": 1, "O": 2, START_TAG: 3, STOP_TAG: 4}

In [23]:
precheck_sent = prepare_sequence(training_data[1][0], word_to_ix)
precheck_sent

tensor([11, 12, 13, 14, 15, 16, 11])

In [24]:
precheck_tags = torch.tensor([tag_to_ix[t] for t in training_data[0][1]],
                            dtype=torch.long)
precheck_tags

tensor([0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 2])

In [26]:
model = BiLSTM_CRF(len(word_to_ix), tag_to_ix, EMBEDDING_DIM, HIDDEN_DIM)

In [27]:
lstm_feates = model._get_lstm_features(precheck_sent)
lstm_feates

tensor([[-0.0940,  0.2521, -0.1978,  0.7061, -0.1087],
        [ 0.0075, -0.0180, -0.3852,  0.5408, -0.0325],
        [-0.2446,  0.3031, -0.3457,  0.4786, -0.3029],
        [-0.2421,  0.1327, -0.3639,  0.5181, -0.2309],
        [-0.4148,  0.1546, -0.4694,  0.4675, -0.0463],
        [-0.2203,  0.2797, -0.2896,  0.4339, -0.6936],
        [-0.1195,  0.1382, -0.2920,  0.4968, -0.5249]],
       grad_fn=<AddmmBackward>)

In [28]:
lstm_feates.size()  # 5是标签长度， 7是文本长度

torch.Size([7, 5])

In [29]:
### 前向算法
init_alphas = torch.full((1, model.tagset_size), -10000.)
init_alphas

tensor([[-10000., -10000., -10000., -10000., -10000.]])

In [30]:
init_alphas[0][model.tag_to_ix[START_TAG]] = 0.
init_alphas

tensor([[-10000., -10000., -10000.,      0., -10000.]])

In [31]:
forward_var = init_alphas

In [40]:
for feat in lstm_feates:
    alphas_t = []
    for next_tag in range(model.tagset_size):
        emit_score = feat[next_tag].view(1, 
                                -1).expand(1, model.tagset_size)
        #print(emit_score)
        #break
        trans_score = model.transitions[next_tag].view(1, -1)
        # print(trans_score)
        # break
        next_tag_var = forward_var + trans_score + emit_score
        
        alphas_t.append(log_sum_exp(next_tag_var).view(1))
    # 改变
    forward_var = torch.cat(alphas_t).view(1, -1)
alphas_t

[tensor([4.3112], grad_fn=<ViewBackward>),
 tensor([5.4447], grad_fn=<ViewBackward>),
 tensor([5.2821], grad_fn=<ViewBackward>),
 tensor([-9993.8789], grad_fn=<ViewBackward>),
 tensor([4.6432], grad_fn=<ViewBackward>)]

In [34]:
terminal_var = torch.cat(alphas_t).view(1, -1)

tensor([-0.1195,  0.1382, -0.2920,  0.4968, -0.5249], grad_fn=<SelectBackward>)

In [38]:
model.transitions

Parameter containing:
tensor([[-1.1811e-01, -1.4420e+00, -1.1108e+00, -1.1187e+00, -1.0000e+04],
        [-4.9566e-01, -1.9700e-01, -3.3396e-02,  1.4273e+00, -1.0000e+04],
        [-7.5307e-01, -4.3190e-01,  6.6930e-01,  6.5051e-01, -1.0000e+04],
        [-1.0000e+04, -1.0000e+04, -1.0000e+04, -1.0000e+04, -1.0000e+04],
        [ 1.8568e-01, -2.7636e-01, -5.9385e-01, -3.0606e-01, -1.0000e+04]],
       requires_grad=True)

In [41]:
model.word_embeds

Embedding(17, 5)

In [44]:
embeds = model.word_embeds(precheck_sent).view(len(precheck_sent), 1, -1)
embeds.size()

torch.Size([7, 1, 5])

In [43]:
sentence

['georgia', 'tech', 'is', 'a', 'university', 'in', 'georgia']

In [46]:
hidden = model.init_hidden()
hidden

(tensor([[[-0.1786, -0.3710]],
 
         [[-0.5775,  0.3241]]]), tensor([[[ 0.6319,  0.1522]],
 
         [[-1.2962,  0.9093]]]))

In [47]:
lstm_output, hidden = model.lstm(embeds, hidden)

In [48]:
lstm_output.size()

torch.Size([7, 1, 4])

In [60]:
lstm_out = lstm_output.view(len(precheck_sent), model.hidden_dim)
lstm_out.size()

torch.Size([7, 4])

In [61]:
lstm_feates = model.hidden2tag(lstm_out)
lstm_feates.size()

torch.Size([7, 5])

In [49]:
from pytorch_pretrained_bert import BertModel
bert = BertModel.from_pretrained('bert-base-chinese')

In [50]:
precheck_sent

tensor([11, 12, 13, 14, 15, 16, 11])

In [52]:
from utils import NerDataset
training_data = NerDataset('./processed/processed_training_bio.txt')
training_data[0]

('[CLS] ， 患 者 3 月 前 因 “ 直 肠 癌 ” 于 在 我 院 于 全 麻 上 行 直 肠 癌 根 治 术 （ D I X O N 术 ） ， 手 术 过 程 顺 利 ， 术 后 给 予 抗 感 染 及 营 养 支 持 治 疗 ， 患 者 恢 复 好 ， 切 口 愈 合 良 好 [SEP]',
 [101,
  8024,
  2642,
  5442,
  124,
  3299,
  1184,
  1728,
  100,
  4684,
  5499,
  4617,
  100,
  754,
  1762,
  2769,
  7368,
  754,
  1059,
  7937,
  677,
  6121,
  4684,
  5499,
  4617,
  3418,
  3780,
  3318,
  8020,
  146,
  151,
  166,
  157,
  156,
  3318,
  8021,
  8024,
  2797,
  3318,
  6814,
  4923,
  7556,
  1164,
  8024,
  3318,
  1400,
  5314,
  750,
  2834,
  2697,
  3381,
  1350,
  5852,
  1075,
  3118,
  2898,
  3780,
  4545,
  8024,
  2642,
  5442,
  2612,
  1908,
  1962,
  8024,
  1147,
  1366,
  2689,
  1394,
  5679,
  1962,
  102],
 [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
 

In [54]:
for batch in train_iter:
    data = batch
    break
data

(['[CLS] 患 者 输 注 氨 磷 汀 恶 心 ， 停 输 [SEP]',
  '[CLS] 自 第 下 次 化 疗 结 束 出 院 以 来 ， 患 者 未 诉 明 显 不 适 ， 一 般 情 况 保 持 良 好 ； 无 发 热 ， 无 恶 心 、 呕 吐 ， 无 反 酸 、 嗳 气 ， 无 明 显 进 食 不 适 ， 未 现 明 显 腹 痛 、 腹 胀 [SEP]',
  '[CLS] 此 次 为 化 疗 再 次 入 院 [SEP]',
  '[CLS] 下 次 出 院 以 来 精 神 、 睡 眠 、 饮 食 可 ， 无 腹 痛 、 腹 胀 、 发 热 ， 大 小 便 正 常 ， 体 重 较 前 无 明 显 变 化 [SEP]',
  '[CLS] B-PAT 一 站 淋 巴 结 （ 8 个 ） 未 查 见 癌 [SEP]',
  '[CLS] 肝 内 多 发 结 节 ， 考 虑 转 移 瘤 ， 部 分 较 前 新 发 ， 肝 S 4 病 灶 较 前 增 大 [SEP]',
  '[CLS] 病 理 诊 断 O （ 胃 窦 ） 慢 性 萎 缩 性 胃 炎 （ 中 度 ） ， 局 部 腺 体 肠 下 皮 化 生 [SEP]',
  '[CLS] ， 缘 于 入 院 前 4 月 余 于 我 院 诊 断 为 胃 窦 癌 ， 于 2 0 1 5 年 0 8 月 2 5 日 在 全 麻 上 行 “ 腹 腔 镜 辅 助 上 根 治 性 远 端 胃 大 部 切 除 + 残 胃 空 肠 R O U X - Y 吻 合 术 （ D 2 ） + 阑 尾 切 除 术 ” ， 手 术 顺 利 [SEP]'],
 tensor([[ 101, 2642, 5442, 6783, 3800, 3710, 4840, 3722, 2626, 2552, 8024,  977,
          6783,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,

In [55]:
words, x, is_heads, tags, y, seqlens = data
x.size()

torch.Size([8, 85])

In [58]:
encoded_layers, _ = bert(x)
enc = encoded_layers[-1]
enc.size()

torch.Size([8, 85, 768])

In [63]:
fc = nn.Linear(768, 16)
lstm_feats = fc(enc)
lstm_feats.size()

torch.Size([8, 85, 16])

In [64]:
lstm_out

tensor([[ 0.2317, -0.3432, -0.2300,  0.2327],
        [ 0.0843, -0.6124,  0.0237,  0.0466],
        [ 0.0817, -0.0319, -0.0956, -0.0518],
        [-0.0460, -0.2713,  0.0071,  0.1377],
        [ 0.0196, -0.1559,  0.4119,  0.0321],
        [-0.2767,  0.0784, -0.5070,  0.1274],
        [-0.2274, -0.2640, -0.4283,  0.2956]], grad_fn=<ViewBackward>)

In [ ]:
forward_score = model._score_sentence(lstm_feates, )

In [66]:
precheck_tags

tensor([0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 2])

In [67]:
gold_score = model._score_sentence(lstm_feates, precheck_tags)
gold_score

tensor([-2.3651], grad_fn=<AddBackward0>)

In [68]:
score = torch.zeros(1)
score

tensor([0.])

In [69]:
tags = torch.cat([torch.tensor([model.tag_to_ix[START_TAG]],
                              dtype=torch.long), precheck_tags])
tags

tensor([3, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 2])

In [71]:
for i, feat in enumerate(lstm_feates):
    score = score + model.transitions[tags[i+1], tags[i]] + feat[tags[i+1]]
score

tensor([-1.7712], grad_fn=<AddBackward0>)

In [72]:
score = score + model.transitions[model.tag_to_ix[STOP_TAG], tags[-1]]
score

tensor([-2.3651], grad_fn=<AddBackward0>)

In [1]:
from crf import Bert_BiLSTM_CRF, tag2idx, log_sum_exp
bert_crf = Bert_BiLSTM_CRF(tag2idx)

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.


In [2]:
from utils import NerDataset
train_dataset = NerDataset('./processed/processed_training_bio.txt')
train_dataset[0]

('[CLS] ， 患 者 3 月 前 因 “ 直 肠 癌 ” 于 在 我 院 于 全 麻 上 行 直 肠 癌 根 治 术 （ D I X O N 术 ） ， 手 术 过 程 顺 利 ， 术 后 给 予 抗 感 染 及 营 养 支 持 治 疗 ， 患 者 恢 复 好 ， 切 口 愈 合 良 好 [SEP]',
 [101,
  8024,
  2642,
  5442,
  124,
  3299,
  1184,
  1728,
  100,
  4684,
  5499,
  4617,
  100,
  754,
  1762,
  2769,
  7368,
  754,
  1059,
  7937,
  677,
  6121,
  4684,
  5499,
  4617,
  3418,
  3780,
  3318,
  8020,
  146,
  151,
  166,
  157,
  156,
  3318,
  8021,
  8024,
  2797,
  3318,
  6814,
  4923,
  7556,
  1164,
  8024,
  3318,
  1400,
  5314,
  750,
  2834,
  2697,
  3381,
  1350,
  5852,
  1075,
  3118,
  2898,
  3780,
  4545,
  8024,
  2642,
  5442,
  2612,
  1908,
  1962,
  8024,
  1147,
  1366,
  2689,
  1394,
  5679,
  1962,
  102],
 [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
 

In [3]:
from torch.utils.data import DataLoader
from utils import pad
train_iter = DataLoader(dataset=train_dataset,
                       batch_size=8,
                       shuffle=True,
                       collate_fn=pad)

In [4]:
for batch in train_iter:
    print(batch)
    break

(['[CLS] O 现 进 食 、 体 力 可 ， 无 明 显 不 适 ， 一 般 情 况 可 [SEP]', '[CLS] 于 2 0 1 4 - 0 5 - 0 5 日 行 术 后 第 1 周 期 化 疗 ， 化 疗 方 案 为 “ X E L O X ” ， ， 具 体 为 ： 奥 沙 利 铂 （ 乐 沙 定 ） 2 4 0 M G O D 1 + 卡 陪 他 滨 片 3 片 O 2 / 日 O D 1 - 1 4 [SEP]', '[CLS] 近 1 年 来 ， 患 者 反 复 因 喘 累 、 气 促 在 我 院 住 院 治 疗 ， 予 以 改 善 循 环 、 利 尿 、 营 养 心 肌 等 对 症 治 疗 后 好 转 出 院 [SEP]', '[CLS] ， 术 中 腹 腔 冲 洗 液 送 快 速 病 理 检 查 结 果 提 示 ： （ 腹 腔 冲 洗 液 ） 离 心 涂 片 查 见 大 量 间 皮 细 胞 及 少 量 淋 巴 细 胞 、 中 性 粒 细 胞 [SEP]', '[CLS] 2 0 1 1 . 6 . 1 0 ， 复 查 C T 示 ： 肝 S 4 病 灶 ， 考 虑 转 移 瘤 [SEP]', '[CLS] 外 院 影 像 学 检 查 提 示 肝 肺 多 发 转 移 , 分 期 C T 4 N 1 M 1 I V 期 [SEP]', '[CLS] 查 无 化 疗 禁 忌 后 于 2 0 1 7 - 0 3 - 0 5 开 始 给 予 规 律 化 疗 5 周 期 ， ， 方 案 为 ： 奥 沙 利 铂 2 0 0 M G O D 1 ， 亚 叶 酸 钙 0 . 3 G + 氟 尿 嘧 啶 0 . 7 5 G O D 2 - D 6 ， 同 时 给 与 升 白 细 胞 、 护 肝 、 止 吐 、 免 疫 增 强 治 疗 ， 患 者 副 反 应 轻 [SEP]', '[CLS] 第 4 程 化 疗 后 出 现 I I I ° 血 小 板 上 降 ， 予 升 血 小 板 治 疗 后 恢 复 [SEP]'], tensor([[ 101,  157, 4385, 6822, 7608,  510,  860, 1213, 1377, 8024, 3187, 3209,
         3227,  679, 6844, 8024,  671, 5

In [5]:
words, x, is_heads, tags, y, seqlens = batch
x

tensor([[ 101,  157, 4385, 6822, 7608,  510,  860, 1213, 1377, 8024, 3187, 3209,
         3227,  679, 6844, 8024,  671, 5663, 2658, 1105, 1377,  102,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0],
        [ 101,  754,  123,  121,  122,  125,  118,  121,  126,  118,  121,  126,
         3189, 6121, 3318, 1400, 5018,  122, 1453, 3309, 1265, 4545, 8024, 1265,
         4545, 3175, 3428,  711,  100,  166,  147,  154,  157,  166,  100, 8024,
         8024, 1072,  860,  711, 8038, 1952, 3763, 1164, 

In [6]:
y

tensor([[ 1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
          3,  3,  3,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
          3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
          3,  3,  3,  3,  3, 12, 13, 13, 13,  3, 12, 13, 13,  3,  3,  3,  3,  3,
          3,  3,  3,  3,  3, 12, 13, 13, 13, 13,  3,  3,  3,  3,  3,  3,  3,  3,
          3,  3,  3,  3,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  

In [7]:
score = bert_crf.neg_log_likelihood(x, y)
score

tensor(9085.1611, grad_fn=<MeanBackward1>)

In [8]:
bert_crf(x)

(tensor([184.2098, 185.2024, 185.0845, 184.9065, 185.0182, 184.8205, 186.4415,
         184.5492], grad_fn=<MaxBackward0>),
 tensor([[ 1,  4, 11, 14,  0,  7, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,
           0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4,
          11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,
           7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11,
          14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,
           4, 11, 14,  0,  7,  4, 11, 13, 12,  4, 11, 14,  0],
         [ 1,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11,
          14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,
           4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,
           0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4,
          11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 14,  0,  7,  4, 11, 1

In [1]:
from crf import Bert_BiLSTM_CRF
from utils import tag2idx, NerDataset
from torch.utils.data import DataLoader
train_dataset = NerDataset('./processed/processed_training_bio.txt')

Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.


In [2]:
from utils import pad
train_iter = DataLoader(dataset=train_dataset,
                       batch_size=8,
                       shuffle=True,
                       collate_fn=pad)
model = Bert_BiLSTM_CRF(tag2idx).cuda()

In [3]:
import torch
import torch.nn as nn
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-4)
criterion = nn.CrossEntropyLoss(ignore_index=0) 

In [4]:
model.train()
device = torch.device('cuda')
for i, batch in enumerate(train_iter):
    words, x, is_heads, tags, y, seqlens = batch
    #print(x, y)
    x = x.to(device)
    y = y.to(device)
    _y = y
    loss = model.neg_log_likelihood(x, y)
    print(loss)
    break

tensor(8897.2734, device='cuda:0', grad_fn=<MeanBackward1>)


In [5]:
x

tensor([[ 101,  125,  119, 5541, 3491, 7755, 6574, 1872, 4495, 8024, 6956, 1146,
         3491,  860, 3503, 2501, 1359,  100, 8024,  711, 6822,  671, 3635, 6402,
         4545, 3119, 1057, 2769, 4906,  857, 7368,  102,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
        [ 101,  123,  121,  122,  123,  118,  125,  118,  122,  129, 6121,  148,
          157,  154,  148,  157,  166, 3175, 3428, 1265, 4545,  122, 4923, 8024,
          678, 4923, 1265, 4545, 1400, 7755, 7767, 2829, 1169,  121, 2428, 8024,
         4385, 2642, 5442, 6822,  671, 3635, 3780, 4545, 1057, 2769, 7368,  102],
        [ 101, 8024, 6822,  671, 3635, 6121, 5517, 7262, 3466, 3389, 4850, 8038,
         5517, 4977, 3971, 4550, 8024, 8024, 4567, 4415, 1726, 2845, 8038,  856,
         1146, 1265, 5593, 4617,  102,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
        [ 101,  123,  121

In [6]:
x.size()

torch.Size([8, 48])

In [10]:
_, y_hat = model(x)
y_hat.size()

torch.Size([8, 48])

In [8]:
x.size()

torch.Size([8, 48])

In [12]:
y_hat

tensor([[ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10

In [13]:
feats = model._get_lstm_features(x)
feats.size()

torch.Size([8, 48, 16])

In [14]:
feats

tensor([[[ 0.0281, -0.0550,  0.0129,  ...,  0.0615, -0.0504,  0.0224],
         [ 0.0049, -0.0628,  0.0059,  ...,  0.0527, -0.0570,  0.0340],
         [ 0.0045, -0.0653, -0.0185,  ...,  0.0645, -0.0443,  0.0133],
         ...,
         [-0.0142,  0.0064,  0.0490,  ...,  0.0421, -0.0469,  0.0335],
         [-0.0130, -0.0054,  0.0496,  ...,  0.0243, -0.0413,  0.0491],
         [-0.0125, -0.0099,  0.0433,  ...,  0.0061, -0.0358,  0.0691]],

        [[ 0.0536, -0.0673,  0.0237,  ...,  0.0531, -0.0357, -0.0150],
         [ 0.0497, -0.0808,  0.0222,  ...,  0.0301, -0.0420, -0.0147],
         [ 0.0524, -0.0685,  0.0206,  ...,  0.0186, -0.0471, -0.0395],
         ...,
         [ 0.0794, -0.0296,  0.0945,  ...,  0.0249, -0.0500, -0.0042],
         [ 0.0957, -0.0198,  0.0715,  ...,  0.0150, -0.0410,  0.0012],
         [ 0.0907, -0.0243,  0.0436,  ..., -0.0034, -0.0302,  0.0141]],

        [[ 0.0062, -0.0408, -0.0195,  ...,  0.0777, -0.0781,  0.0116],
         [-0.0052, -0.0541, -0.0196,  ...,  0

In [15]:
forward_score = model._forward_alg(feats)
forward_score

tensor([[147.9133],
        [147.4303],
        [148.0974],
        [147.7309],
        [148.1846],
        [147.8042],
        [148.2599],
        [147.7885]], device='cuda:0', grad_fn=<ThAddBackward>)

In [39]:
T = feats.shape[1]  # 48
batch_size = feats.shape[0] # 8
log_alpha = torch.Tensor(batch_size, 1, model.tagset_size).fill_(-10000.).to(device)
log_alpha

tensor([[[-10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -1000

In [40]:
log_alpha.size()

torch.Size([8, 1, 16])

In [41]:
log_alpha[:, 0, model.start_label_id] = 0  # start
log_alpha

tensor([[[-10000.,      0., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000.,      0., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000.,      0., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000.,      0., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000.,      0., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000.]],

        [[-10000.,      0., -10000., -10000., -10000., -10000., -10000.,
          -10000., -10000., -10000., -1000

In [28]:
from crf import log_sum_exp_batch
for t in range(1, T):
    log_alpha = (log_sum_exp_batch(model.transitions + log_alpha, axis=-1) + \
                feats[:, t]).unsqueeze(1)
log_alpha

tensor([[[  144.8641, -9855.2334,   145.5775,   145.0860,   144.8228,
            144.7302,   145.1429,   144.9583,   145.7245,   144.4912,
            145.4246,   145.1542,   145.1834,   145.8036,   144.8662,
            145.2539]],

        [[  144.4784, -9855.7197,   145.1395,   144.5858,   144.3716,
            144.2122,   144.6883,   144.4500,   145.2439,   144.0007,
            144.9102,   144.6417,   144.7353,   145.2937,   144.3879,
            144.7162]],

        [[  145.0520, -9855.0391,   145.7509,   145.2805,   145.0079,
            144.9183,   145.3147,   145.1641,   145.9079,   144.6948,
            145.6046,   145.3418,   145.3606,   145.9893,   145.0412,
            145.4357]],

        [[  144.7064, -9855.4033,   145.3721,   144.9241,   144.6285,
            144.5308,   144.9641,   144.7639,   145.5438,   144.3062,
            145.2186,   145.0020,   145.0001,   145.6365,   144.6976,
            145.0546]],

        [[  145.1684, -9854.9326,   145.8189,   145.3871,   

In [29]:
log_prob_all_barX = log_sum_exp_batch(log_alpha)
log_prob_all_barX

tensor([[147.9133],
        [147.4303],
        [148.0974],
        [147.7309],
        [148.1846],
        [147.8042],
        [148.2599],
        [147.7885]], device='cuda:0', grad_fn=<ThAddBackward>)

In [33]:
log_tensor = model.transitions + log_alpha
log_tensor

tensor([[[-10000.7930, -10001.8008, -20000.0000,  ..., -10000.0947,
          -10000.1084,  -9999.3965],
         [-20000.0000, -20000.0000, -20000.0000,  ..., -20000.0000,
          -20000.0000, -20000.0000],
         [ -9997.2207, -10001.1709, -20000.0000,  ...,  -9999.9961,
          -10000.9746,  -9999.8389],
         ...,
         [-10000.2920,  -9999.9307, -20000.0000,  ...,  -9999.2432,
           -9999.7842,  -9997.3965],
         [-10000.8906,  -9998.4971, -20000.0000,  ..., -10001.6738,
           -9999.9238,  -9998.8242],
         [-10000.2871,  -9998.6035, -20000.0000,  ..., -10000.3848,
          -10000.5771, -10000.4688]],

        [[-10000.7930, -10001.8008, -20000.0000,  ..., -10000.0947,
          -10000.1084,  -9999.3965],
         [-20000.0000, -20000.0000, -20000.0000,  ..., -20000.0000,
          -20000.0000, -20000.0000],
         [ -9997.2207, -10001.1709, -20000.0000,  ...,  -9999.9961,
          -10000.9746,  -9999.8389],
         ...,
         [-10000.2920,  -

In [38]:
torch.max(log_tensor, -1)[0]

tensor([[ -9998.9668, -20000.0000,  -9997.2207,  -9998.3428,  -9998.9639,
          -9998.6035,  -9998.2314,  -9998.5029,  -9997.5801,  -9998.6475,
          -9997.7178,  -9997.9062,  -9998.1299,  -9997.3965,  -9998.4971,
          -9997.1680],
        [ -9998.9668, -20000.0000,  -9997.2207,  -9998.3428,  -9998.9639,
          -9998.6035,  -9998.2314,  -9998.5029,  -9997.5801,  -9998.6475,
          -9997.7178,  -9997.9062,  -9998.1299,  -9997.3965,  -9998.4971,
          -9997.1680],
        [ -9998.9668, -20000.0000,  -9997.2207,  -9998.3428,  -9998.9639,
          -9998.6035,  -9998.2314,  -9998.5029,  -9997.5801,  -9998.6475,
          -9997.7178,  -9997.9062,  -9998.1299,  -9997.3965,  -9998.4971,
          -9997.1680],
        [ -9998.9668, -20000.0000,  -9997.2207,  -9998.3428,  -9998.9639,
          -9998.6035,  -9998.2314,  -9998.5029,  -9997.5801,  -9998.6475,
          -9997.7178,  -9997.9062,  -9998.1299,  -9997.3965,  -9998.4971,
          -9997.1680],
        [ -9998.9668

In [43]:
log_alpha.size()

torch.Size([8, 1, 16])

In [45]:
enc = model._bert_enc(x)
enc.size()

torch.Size([8, 48, 768])

In [46]:
enc[:, 1:-1, :].size()

torch.Size([8, 46, 768])

In [47]:
enc, _ = model.lstm(enc[:, 1:-1, :])
feats = model.fc(enc)
feats.size()

torch.Size([8, 46, 16])

In [48]:
score, tag_seq = model._viterbi_decode(feats)
score

tensor([ 99.8801, 100.5272,  99.8877,  99.9009,  99.8440, 100.6436, 100.8326,
        101.1094], device='cuda:0', grad_fn=<MaxBackward0>)

In [49]:
tag_seq

tensor([[ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [ 1,  6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10